name: cli_time_track
description: Time tracking in yaml file.
repository: https://github.com/spidgorny/cli_time_track

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

executables:
  ttrack: ttrack

dependencies:
  flutter:
    sdk: flutter

  yaml: ^2.2.1
  duration: ^2.0.15
  date_calendar: ^0.2.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.7.0
